// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pro11WA.Models;

namespace Pro11WA.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Pro11WA.Models.Furnace", b =>
                {
                    b.Property<int>("furnaceid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("companyid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("manufacturersCompanyId")
                        .HasColumnType("int");

                    b.Property<string>("modelnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serialnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("size")
                        .HasColumnType("int");

                    b.Property<double>("tonnage")
                        .HasColumnType("float");

                    b.Property<int>("year")
                        .HasColumnType("int");

                    b.HasKey("furnaceid");

                    b.HasIndex("manufacturersCompanyId");

                    b.ToTable("Furnaces");
                });

            modelBuilder.Entity("Pro11WA.Models.Manufacturers", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyProducts")
                        .HasColumnType("int");

                    b.HasKey("CompanyId");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("Pro11WA.Models.Furnace", b =>
                {
                    b.HasOne("Pro11WA.Models.Manufacturers", "manufacturers")
                        .WithMany("Furnaces")
                        .HasForeignKey("manufacturersCompanyId");
                });
#pragma warning restore 612, 618
        }
    }
}
